# Generated by Django 5.1.5 on 2025-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="image",
            field=models.ImageField(default="default", upload_to="candidates/"),
            preserve_default=False,
        ),
    ]
